name: "QA Assistant Action"
description: "QA Assistant Action for GitHub CI/CD"

inputs:
  key:
    description: 'Qwen model access key'
    required: true
  action-name:
    description: 'QA Assistant action name'
    required: true
    default: 'INDEX' # INDEX/PLAN/JUNIT_UPDATE
  target-value:
    description: 'Target value in percent'
    required: true
    default: '80'
  test-report-dir:
    description: 'Path to test report files'
    required: true
    default: './target/surefire-reports/*.xml'
  coverage-report-dir:
    description: 'Path to coverage report files'
    required: true
    default: './target/site/jacoco/index.html'
  input-dir:
    description: 'Path to source files'
    required: true
    default: './'
  output-dir:
    description: 'Path to output files'
    required: true
    default: './'

runs:
  using: "docker"
  image: "docker://jacobsonius/qa-assistant:latest"
  args:
    - ${{ inputs.key }}
    - ${{ inputs.action-name }}
    - ${{ inputs.target-value }}
    - ${{ inputs.test-report-dir }}
    - ${{ inputs.coverage-report-dir }}
    - ${{ inputs.input-dir }}
    - ${{ inputs.output-dir }}